// Code generated by protoc-gen-go. DO NOT EDIT.
// source: object_bucket_interface.proto

package cosi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProvisionRequest struct {
	RequestBucketName    string   `protobuf:"bytes,1,opt,name=requestBucketName,proto3" json:"requestBucketName,omitempty"`
	Region               string   `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvisionRequest) Reset()         { *m = ProvisionRequest{} }
func (m *ProvisionRequest) String() string { return proto.CompactTextString(m) }
func (*ProvisionRequest) ProtoMessage()    {}
func (*ProvisionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_056cd8199f3a1065, []int{0}
}

func (m *ProvisionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionRequest.Unmarshal(m, b)
}
func (m *ProvisionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionRequest.Marshal(b, m, deterministic)
}
func (m *ProvisionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionRequest.Merge(m, src)
}
func (m *ProvisionRequest) XXX_Size() int {
	return xxx_messageInfo_ProvisionRequest.Size(m)
}
func (m *ProvisionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionRequest proto.InternalMessageInfo

func (m *ProvisionRequest) GetRequestBucketName() string {
	if m != nil {
		return m.RequestBucketName
	}
	return ""
}

func (m *ProvisionRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

type ProvisionResponse struct {
	BucketName             string            `protobuf:"bytes,1,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	Endpoint               string            `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Region                 string            `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	EnvironmentCredentials map[string]string `protobuf:"bytes,5,rep,name=environmentCredentials,proto3" json:"environmentCredentials,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Data                   map[string]string `protobuf:"bytes,6,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral   struct{}          `json:"-"`
	XXX_unrecognized       []byte            `json:"-"`
	XXX_sizecache          int32             `json:"-"`
}

func (m *ProvisionResponse) Reset()         { *m = ProvisionResponse{} }
func (m *ProvisionResponse) String() string { return proto.CompactTextString(m) }
func (*ProvisionResponse) ProtoMessage()    {}
func (*ProvisionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_056cd8199f3a1065, []int{1}
}

func (m *ProvisionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionResponse.Unmarshal(m, b)
}
func (m *ProvisionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionResponse.Marshal(b, m, deterministic)
}
func (m *ProvisionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionResponse.Merge(m, src)
}
func (m *ProvisionResponse) XXX_Size() int {
	return xxx_messageInfo_ProvisionResponse.Size(m)
}
func (m *ProvisionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionResponse proto.InternalMessageInfo

func (m *ProvisionResponse) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *ProvisionResponse) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *ProvisionResponse) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *ProvisionResponse) GetEnvironmentCredentials() map[string]string {
	if m != nil {
		return m.EnvironmentCredentials
	}
	return nil
}

func (m *ProvisionResponse) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeprovisionRequest struct {
	BucketName           string   `protobuf:"bytes,1,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeprovisionRequest) Reset()         { *m = DeprovisionRequest{} }
func (m *DeprovisionRequest) String() string { return proto.CompactTextString(m) }
func (*DeprovisionRequest) ProtoMessage()    {}
func (*DeprovisionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_056cd8199f3a1065, []int{2}
}

func (m *DeprovisionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeprovisionRequest.Unmarshal(m, b)
}
func (m *DeprovisionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeprovisionRequest.Marshal(b, m, deterministic)
}
func (m *DeprovisionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeprovisionRequest.Merge(m, src)
}
func (m *DeprovisionRequest) XXX_Size() int {
	return xxx_messageInfo_DeprovisionRequest.Size(m)
}
func (m *DeprovisionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeprovisionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeprovisionRequest proto.InternalMessageInfo

func (m *DeprovisionRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

type DeprovisionResponse struct {
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeprovisionResponse) Reset()         { *m = DeprovisionResponse{} }
func (m *DeprovisionResponse) String() string { return proto.CompactTextString(m) }
func (*DeprovisionResponse) ProtoMessage()    {}
func (*DeprovisionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_056cd8199f3a1065, []int{3}
}

func (m *DeprovisionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeprovisionResponse.Unmarshal(m, b)
}
func (m *DeprovisionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeprovisionResponse.Marshal(b, m, deterministic)
}
func (m *DeprovisionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeprovisionResponse.Merge(m, src)
}
func (m *DeprovisionResponse) XXX_Size() int {
	return xxx_messageInfo_DeprovisionResponse.Size(m)
}
func (m *DeprovisionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeprovisionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeprovisionResponse proto.InternalMessageInfo

func (m *DeprovisionResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ProvisionRequest)(nil), "cosi.ProvisionRequest")
	proto.RegisterType((*ProvisionResponse)(nil), "cosi.ProvisionResponse")
	proto.RegisterMapType((map[string]string)(nil), "cosi.ProvisionResponse.DataEntry")
	proto.RegisterMapType((map[string]string)(nil), "cosi.ProvisionResponse.EnvironmentCredentialsEntry")
	proto.RegisterType((*DeprovisionRequest)(nil), "cosi.DeprovisionRequest")
	proto.RegisterType((*DeprovisionResponse)(nil), "cosi.DeprovisionResponse")
}

func init() { proto.RegisterFile("object_bucket_interface.proto", fileDescriptor_056cd8199f3a1065) }

var fileDescriptor_056cd8199f3a1065 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x4f, 0xea, 0x40,
	0x10, 0xc6, 0x5f, 0x29, 0xf0, 0x1e, 0xc3, 0x05, 0xe6, 0xbd, 0xf0, 0x6a, 0x8d, 0x06, 0x7b, 0xe2,
	0x60, 0x6a, 0x02, 0x1a, 0x8d, 0x07, 0x0f, 0x0a, 0x07, 0x2f, 0xc6, 0x70, 0xf2, 0x46, 0xb6, 0x65,
	0x24, 0x2b, 0xb0, 0x5b, 0x77, 0x17, 0x12, 0xfe, 0x0a, 0x0f, 0xfe, 0xc3, 0x86, 0xb6, 0x34, 0x95,
	0x82, 0xc6, 0xdb, 0x7e, 0xdd, 0x99, 0xdf, 0xcc, 0x7e, 0x5f, 0xe1, 0x48, 0x06, 0x2f, 0x14, 0x9a,
	0x51, 0xb0, 0x08, 0xa7, 0x64, 0x46, 0x5c, 0x18, 0x52, 0xcf, 0x2c, 0x24, 0x3f, 0x52, 0xd2, 0x48,
	0x2c, 0x87, 0x52, 0x73, 0xef, 0x09, 0x1a, 0x8f, 0x4a, 0x2e, 0xb9, 0xe6, 0x52, 0x0c, 0xe9, 0x75,
	0x41, 0xda, 0xe0, 0x29, 0x34, 0x55, 0x72, 0xbc, 0x8d, 0x5b, 0x1f, 0xd8, 0x9c, 0x1c, 0xab, 0x6d,
	0x75, 0x6a, 0xc3, 0xe2, 0x05, 0xb6, 0xa0, 0xaa, 0x68, 0xc2, 0xa5, 0x70, 0x4a, 0x71, 0x49, 0xaa,
	0xbc, 0x37, 0x1b, 0x9a, 0x39, 0xb4, 0x8e, 0xa4, 0xd0, 0x84, 0xc7, 0x00, 0xc1, 0x36, 0x34, 0xf7,
	0x05, 0x5d, 0xf8, 0x43, 0x62, 0x1c, 0x49, 0x2e, 0x4c, 0xca, 0xcb, 0x74, 0x6e, 0x92, 0x9d, 0x9f,
	0x84, 0x53, 0x68, 0x91, 0x58, 0x72, 0x25, 0xc5, 0x9c, 0x84, 0xb9, 0x53, 0x34, 0x26, 0x61, 0x38,
	0x9b, 0x69, 0xa7, 0xd2, 0xb6, 0x3b, 0xf5, 0x6e, 0xcf, 0x5f, 0x3f, 0xd5, 0x2f, 0x2c, 0xe3, 0x0f,
	0x76, 0x76, 0x0d, 0x84, 0x51, 0xab, 0xe1, 0x1e, 0x24, 0x5e, 0x40, 0x79, 0xcc, 0x0c, 0x73, 0xaa,
	0x31, 0xfa, 0x64, 0x1f, 0xba, 0xcf, 0x0c, 0x4b, 0x40, 0x71, 0xb9, 0x7b, 0x0f, 0x87, 0x5f, 0x4c,
	0xc3, 0x06, 0xd8, 0x53, 0x5a, 0xa5, 0x7e, 0xac, 0x8f, 0xf8, 0x0f, 0x2a, 0x4b, 0x36, 0x5b, 0x50,
	0xea, 0x42, 0x22, 0xae, 0x4b, 0x57, 0x96, 0x7b, 0x09, 0xb5, 0x8c, 0xfe, 0x93, 0x46, 0xef, 0x1c,
	0xb0, 0x4f, 0xd1, 0x76, 0xda, 0xdf, 0x24, 0xe2, 0x9d, 0xc1, 0xdf, 0x4f, 0x5d, 0x69, 0x90, 0x0e,
	0xfc, 0x9e, 0x93, 0xd6, 0x6c, 0x42, 0x69, 0x1a, 0x1b, 0xd9, 0x7d, 0xb7, 0xa0, 0x9e, 0x19, 0x42,
	0x0a, 0x6f, 0xa0, 0x96, 0x49, 0x6c, 0x15, 0x0c, 0x8b, 0xb7, 0x70, 0xff, 0xef, 0x31, 0xd2, 0xfb,
	0x85, 0x7d, 0xa8, 0xe7, 0x16, 0x40, 0x27, 0xa9, 0x2c, 0xbe, 0xc4, 0x3d, 0xd8, 0x71, 0xb3, 0xa1,
	0x04, 0xd5, 0xf8, 0xaf, 0xef, 0x7d, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe7, 0xa2, 0xd7, 0x80, 0x16,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProvisionerClient is the client API for Provisioner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProvisionerClient interface {
	Provision(ctx context.Context, in *ProvisionRequest, opts ...grpc.CallOption) (*ProvisionResponse, error)
	Deprovision(ctx context.Context, in *DeprovisionRequest, opts ...grpc.CallOption) (*DeprovisionResponse, error)
}

type provisionerClient struct {
	cc *grpc.ClientConn
}

func NewProvisionerClient(cc *grpc.ClientConn) ProvisionerClient {
	return &provisionerClient{cc}
}

func (c *provisionerClient) Provision(ctx context.Context, in *ProvisionRequest, opts ...grpc.CallOption) (*ProvisionResponse, error) {
	out := new(ProvisionResponse)
	err := c.cc.Invoke(ctx, "/cosi.Provisioner/Provision", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionerClient) Deprovision(ctx context.Context, in *DeprovisionRequest, opts ...grpc.CallOption) (*DeprovisionResponse, error) {
	out := new(DeprovisionResponse)
	err := c.cc.Invoke(ctx, "/cosi.Provisioner/Deprovision", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProvisionerServer is the server API for Provisioner service.
type ProvisionerServer interface {
	Provision(context.Context, *ProvisionRequest) (*ProvisionResponse, error)
	Deprovision(context.Context, *DeprovisionRequest) (*DeprovisionResponse, error)
}

// UnimplementedProvisionerServer can be embedded to have forward compatible implementations.
type UnimplementedProvisionerServer struct {
}

func (*UnimplementedProvisionerServer) Provision(ctx context.Context, req *ProvisionRequest) (*ProvisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Provision not implemented")
}
func (*UnimplementedProvisionerServer) Deprovision(ctx context.Context, req *DeprovisionRequest) (*DeprovisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deprovision not implemented")
}

func RegisterProvisionerServer(s *grpc.Server, srv ProvisionerServer) {
	s.RegisterService(&_Provisioner_serviceDesc, srv)
}

func _Provisioner_Provision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionerServer).Provision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosi.Provisioner/Provision",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionerServer).Provision(ctx, req.(*ProvisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provisioner_Deprovision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeprovisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionerServer).Deprovision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosi.Provisioner/Deprovision",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionerServer).Deprovision(ctx, req.(*DeprovisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Provisioner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosi.Provisioner",
	HandlerType: (*ProvisionerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Provision",
			Handler:    _Provisioner_Provision_Handler,
		},
		{
			MethodName: "Deprovision",
			Handler:    _Provisioner_Deprovision_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "object_bucket_interface.proto",
}
